### ISSUE TITLE
Install on 14.10 not working

### ISSUE THREAD

**Issue by MartinHjelm** [jayrambhia/Install-OpenCV#39]
Running the install script I get the following error

--- Installing dependency: libavcodec-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libavcodec-dev : Depends: libavcodec54 (<= 7:1.2.6-99) but it is not going to be installed or
                           libavcodec-extra-54 (<= 7:1.2.6-99) but it is not going to be installed
                  Depends: libavcodec54 (>= 7:1.2.6-1~trusty1) but it is not going to be installed or
                           libavcodec-extra-54 (>= 7:1.2.6-1~trusty1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

It seems that libavc-dev has been removed.

**Comment by srugano** [comment]
Have you used this [solution](http://askubuntu.com/questions/376423/opencv-install-problems-on-studio-12-04-broken-dependencies) while installing libavcodec-dev on Ubuntu 14.04 ?

**Comment by MartinHjelm** [comment]
I dunno what business I had trying to use a non-LTS version so I  downgraded to 14.04.
