### ISSUE TITLE
Uninstall version 3.0.0

### ISSUE THREAD

**Issue by lakehanne** [jayrambhia/Install-OpenCV#46]
Hi,

I installed the version 3.0.0 only to notice it doesn't compile with the calibration library I intend to use. Is there a standard way to purge the system of the 3.0 version and use a previous version?
Thanks!

Lakehanne

**Comment by RaedsLab** [comment]
:+1:

**Comment by lakehanne** [comment]
i have since uninstalled via `make  uninstall` using my installation mnifest. Closing.
