### ISSUE TITLE
Unable to locate package libqt5-dev

### ISSUE THREAD

**Issue by robert604** [jayrambhia/Install-OpenCV#70]
I'm trying to install opencv on ubuntu 16.04.  When I run the script it stops with the message:
"E: Unable to locate package libqt5-dev"

Any help fixing this would be appreciated.

**Comment by shinriyo** [comment]
Hi @robert604

I think `libqt5-dev` repository is not available.
I also met the trouble. :<

I fix `Ubuntu/dependencies.sh` file

```
# install_dependency libqt5-dev
install_dependency libqt5x11extras5
```

I am pull-requesting now 👍 

https://github.com/jayrambhia/Install-OpenCV/pull/71/files

**Comment by mrinalsenapati04** [comment]
Hi @shinriyo 
I am facing the same issue. Can u tell me how to find the Ubuntu/dependencies.sh file in ubuntu 16.04?
