### ISSUE TITLE
Install latest on ubuntu 22.04

### ISSUE THREAD

**Issue by hbonnavaud** [jayrambhia/Install-OpenCV#86]
While following the installation instructions in the readme, I ran into an error error E: Unable to locate package libdc1394-22-dev

But according to https://askubuntu.com/questions/1407580/unable-to-locate-package-libdc1394-22-dev : "The libdc1394-22-dev package was removed in Debian and Ubuntu after 21.10". But I'm on ubuntu 22.04.

Any idea?

**Comment by matanox** [comment]
Was it resolved? I bump into the same when trying to install via:

```bash
sudo apt-get install -y \
    libopencv-core-dev \
    libopencv-highgui-dev \
    libopencv-calib3d-dev \
    libopencv-features2d-dev \
    libopencv-imgproc-dev \
    libopencv-video-dev
```

**Comment by hbonnavaud** [comment]
Hi, no, but I re-installed my system since this issue and found a solution to my problem that doesn't require opencv.

**Comment by matanox** [comment]
That's my plan too.
